theme[main_bg]={{colors.surface.default.hex}}

theme[main_fg]={{colors.on_surface.default.hex}}

theme[title]={{colors.on_surface.default.hex}}

theme[hi_fg]={{colors.primary.default.hex}}

theme[selected_bg]={{colors.surface_container.default.hex}}

theme[selected_fg]={{colors.primary.default.hex}}

theme[inactive_fg]={{colors.outline.default.hex}}

theme[graph_text]={{colors.tertiary.default.hex}}

theme[meter_bg]={{colors.outline.default.hex}}

theme[proc_misc]={{colors.tertiary.default.hex}}

theme[cpu_box]=#c78bff
theme[mem_box]=#a3e635
theme[net_box]=#e08a5f
theme[proc_box]=#7aa2f7

theme[div_line]={{colors.outline_variant.default.hex}}

theme[temp_start]=#a3e635
theme[temp_mid]=#fcd34d
theme[temp_end]=#ff6b6b

theme[cpu_start]=#56cfe1
theme[cpu_mid]=#7aa2f7
theme[cpu_end]={{colors.on_surface.default.hex}}

theme[free_start]=#c78bff
theme[free_mid]={{colors.on_surface.default.hex}}
theme[free_end]=#7aa2f7

theme[cached_start]=#7aa2f7
theme[cached_mid]=#7aa2f7
theme[cached_end]={{colors.on_surface.default.hex}}

theme[available_start]=#fbbf24
theme[available_mid]=#e08a5f
theme[available_end]=#ff6b6b

theme[used_start]=#a3e635
theme[used_mid]=#56cfe1
theme[used_end]=#56cfe1

theme[download_start]=#fbbf24
theme[download_mid]=#e08a5f
theme[download_end]=#ff6b6b

theme[upload_start]=#a3e635
theme[upload_mid]=#56cfe1
theme[upload_end]=#56cfe1

theme[process_start]=#7aa2f7
theme[process_mid]={{colors.on_surface.default.hex}}
theme[process_end]=#c78bff
