# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]={{colors.surface.default.hex}}

# Main text color
theme[main_fg]={{colors.on_surface.default.hex}}

# Title color for boxes
theme[title]={{colors.on_surface.default.hex}}

# Highlight color for keyboard shortcuts
theme[hi_fg]={{colors.primary.default.hex}}

# Background color of selected item in processes box
theme[selected_bg]={{colors.surface_container.default.hex}}

# Foreground color of selected item in processes box
theme[selected_fg]={{colors.primary.default.hex}}

# Color of inactive/disabled text
theme[inactive_fg]={{colors.outline.default.hex}}

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]={{colors.tertiary.default.hex}}

# Background color of the percentage meters
theme[meter_bg]={{colors.outline.default.hex}}

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]={{colors.tertiary.default.hex}}

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#c78bff
theme[mem_box]=#a3e635
theme[net_box]=#e08a5f
theme[proc_box]=#7aa2f7

# Box divider line and small boxes line color
theme[div_line]={{colors.outline_variant.default.hex}}

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#a3e635
theme[temp_mid]=#fcd34d
theme[temp_end]=#ff6b6b

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#56cfe1
theme[cpu_mid]=#7aa2f7
theme[cpu_end]={{colors.on_surface.default.hex}}

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#c78bff
theme[free_mid]={{colors.on_surface.default.hex}}
theme[free_end]=#7aa2f7

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#7aa2f7
theme[cached_mid]=#7aa2f7
theme[cached_end]={{colors.on_surface.default.hex}}

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#fbbf24
theme[available_mid]=#e08a5f
theme[available_end]=#ff6b6b

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#a3e635
theme[used_mid]=#56cfe1
theme[used_end]=#56cfe1

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#fbbf24
theme[download_mid]=#e08a5f
theme[download_end]=#ff6b6b

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#a3e635
theme[upload_mid]=#56cfe1
theme[upload_end]=#56cfe1

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#7aa2f7
theme[process_mid]={{colors.on_surface.default.hex}}
theme[process_end]=#c78bff
