-- Generated by matugen on every wallpaper change -- edits here are lost.
-- The template is dotfiles/matugen/templates/hypr-scheme.lua.
--
-- Keys are camelCase and values carry no leading '#', because that is what
-- hypr/variables.lua interpolates into rgba() strings. hypr/current_scheme.lua
-- gates on `primary` being present and falls back to scheme/default.lua when it
-- is not, which is what keeps a half-written file here from emptying
-- variables.lua and taking every keybind and window rule with it.
--
-- Far more is emitted than is currently read. The cost is a few hundred bytes
-- and it means a new rule can reach for any Material name without a round trip
-- through this template.
return {
  background = "{{colors.background.default.hex_stripped}}",
  onBackground = "{{colors.on_background.default.hex_stripped}}",

  surface = "{{colors.surface.default.hex_stripped}}",
  onSurface = "{{colors.on_surface.default.hex_stripped}}",
  surfaceDim = "{{colors.surface_dim.default.hex_stripped}}",
  surfaceBright = "{{colors.surface_bright.default.hex_stripped}}",
  surfaceContainerLowest = "{{colors.surface_container_lowest.default.hex_stripped}}",
  surfaceContainerLow = "{{colors.surface_container_low.default.hex_stripped}}",
  surfaceContainer = "{{colors.surface_container.default.hex_stripped}}",
  surfaceContainerHigh = "{{colors.surface_container_high.default.hex_stripped}}",
  surfaceContainerHighest = "{{colors.surface_container_highest.default.hex_stripped}}",
  surfaceVariant = "{{colors.surface_variant.default.hex_stripped}}",
  onSurfaceVariant = "{{colors.on_surface_variant.default.hex_stripped}}",
  surfaceTint = "{{colors.surface_tint.default.hex_stripped}}",
  inverseSurface = "{{colors.inverse_surface.default.hex_stripped}}",
  inverseOnSurface = "{{colors.inverse_on_surface.default.hex_stripped}}",

  outline = "{{colors.outline.default.hex_stripped}}",
  outlineVariant = "{{colors.outline_variant.default.hex_stripped}}",
  shadow = "{{colors.shadow.default.hex_stripped}}",
  scrim = "{{colors.scrim.default.hex_stripped}}",

  primary = "{{colors.primary.default.hex_stripped}}",
  onPrimary = "{{colors.on_primary.default.hex_stripped}}",
  primaryContainer = "{{colors.primary_container.default.hex_stripped}}",
  onPrimaryContainer = "{{colors.on_primary_container.default.hex_stripped}}",
  inversePrimary = "{{colors.inverse_primary.default.hex_stripped}}",
  primaryFixed = "{{colors.primary_fixed.default.hex_stripped}}",
  primaryFixedDim = "{{colors.primary_fixed_dim.default.hex_stripped}}",
  onPrimaryFixed = "{{colors.on_primary_fixed.default.hex_stripped}}",
  onPrimaryFixedVariant = "{{colors.on_primary_fixed_variant.default.hex_stripped}}",

  secondary = "{{colors.secondary.default.hex_stripped}}",
  onSecondary = "{{colors.on_secondary.default.hex_stripped}}",
  secondaryContainer = "{{colors.secondary_container.default.hex_stripped}}",
  onSecondaryContainer = "{{colors.on_secondary_container.default.hex_stripped}}",
  secondaryFixed = "{{colors.secondary_fixed.default.hex_stripped}}",
  secondaryFixedDim = "{{colors.secondary_fixed_dim.default.hex_stripped}}",
  onSecondaryFixed = "{{colors.on_secondary_fixed.default.hex_stripped}}",
  onSecondaryFixedVariant = "{{colors.on_secondary_fixed_variant.default.hex_stripped}}",

  tertiary = "{{colors.tertiary.default.hex_stripped}}",
  onTertiary = "{{colors.on_tertiary.default.hex_stripped}}",
  tertiaryContainer = "{{colors.tertiary_container.default.hex_stripped}}",
  onTertiaryContainer = "{{colors.on_tertiary_container.default.hex_stripped}}",
  tertiaryFixed = "{{colors.tertiary_fixed.default.hex_stripped}}",
  tertiaryFixedDim = "{{colors.tertiary_fixed_dim.default.hex_stripped}}",
  onTertiaryFixed = "{{colors.on_tertiary_fixed.default.hex_stripped}}",
  onTertiaryFixedVariant = "{{colors.on_tertiary_fixed_variant.default.hex_stripped}}",

  error = "{{colors.error.default.hex_stripped}}",
  onError = "{{colors.on_error.default.hex_stripped}}",
  errorContainer = "{{colors.error_container.default.hex_stripped}}",
  onErrorContainer = "{{colors.on_error_container.default.hex_stripped}}",

  -- The 16 ANSI slots, mirroring terminal-colors.conf -- greys from the
  -- palette, hues fixed. That template carries the reasoning; the short of it
  -- is that matugen's base16 is a lightness ramp with no hue in it, so a
  -- low-chroma wallpaper turns "green" and "blue" into near-black.
  -- base16 is its own namespace in matugen, not part of colors.
  term0 = "{{base16.base02.default.hex_stripped}}",
  term1 = "ff6b6b",
  term2 = "a3e635",
  term3 = "fbbf24",
  term4 = "7aa2f7",
  term5 = "c78bff",
  term6 = "56cfe1",
  term7 = "{{base16.base06.default.hex_stripped}}",
  term8 = "{{base16.base04.default.hex_stripped}}",
  term9 = "ff8787",
  term10 = "bef264",
  term11 = "fcd34d",
  term12 = "9db4f9",
  term13 = "d8a5ff",
  term14 = "7ae0ee",
  term15 = "{{base16.base07.default.hex_stripped}}",
}
